name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: [README.md]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Local Action
      uses: ./
      with:
        tests: sample-test.sh
        url: https://duckduckgo.com
